services:
  avia-calendar:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8796:8796
    command: ["-proxy", "socks5://tor:9050"]
  tor:
    restart: always
    build: ./tor