services:
  avia-calendar:
    restart: always
    build: ./
    command: ["-proxy", "socks5://tor:9050"]
    networks:
      - traefik-gateway
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-gateway
      - traefik.http.routers.avia-calendar.rule=Host(`avia-calendar.dynlink.online`)
      - traefik.http.services.avia-calendar.loadbalancer.server.port=8796
  tor:
    restart: always
    build: ./tor
    networks:
      - default

networks:
  traefik-gateway:
    external: true
  default: